apiVersion: v1
kind: Service
metadata:
  name: vrsky-ui
  namespace: vrsky-ui
  labels:
    app: vrsky-ui
    component: frontend
    phase: "12"

spec:
  type: ClusterIP
  selector:
    app: vrsky-ui
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  sessionAffinity: None
