package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// Gateway rate limiting (#90). The management-API owns the per-tenant → plan
// mapping; Traefik enforces the limit at the edge. We render a Traefik
// file-provider dynamic config (one router per tenant, matched on the
// X-Tenant-ID header, attaching that tenant's plan middleware) and write it
// atomically into TRAEFIK_DYNAMIC_DIR. Traefik's file watcher hot-reloads it in
// ~1-2s — no restart — so a plan change propagates well within the 30s target.
//
// The base middlewares (rl-free/rl-pro/rl-enterprise) and the management-api
// service live in the static base config (infrastructure/traefik/dynamic/base.yml).

// middlewareForPlan maps a subscription plan to its Traefik rate-limit middleware.
func middlewareForPlan(plan string) string {
	switch plan {
	case "pro":
		return "rl-pro"
	case "enterprise":
		return "rl-enterprise"
	default:
		return "rl-free" // free + any unknown value
	}
}

// renderTenantGatewayConfig renders the Traefik dynamic config (YAML) mapping
// each tenant to its plan's rate-limit middleware.
func renderTenantGatewayConfig(plans map[string]string) string {
	var b strings.Builder
	b.WriteString("# Generated by management-api (#90) — do not edit by hand.\n")
	b.WriteString("http:\n")

	ids := make([]string, 0, len(plans))
	for id := range plans {
		ids = append(ids, id)
	}
	sort.Strings(ids) // deterministic output

	if len(ids) == 0 {
		b.WriteString("  routers: {}\n")
		return b.String()
	}

	b.WriteString("  routers:\n")
	for _, id := range ids {
		mw := middlewareForPlan(plans[id])
		fmt.Fprintf(&b, "    tenant-%s:\n", id)
		// Higher priority than the catch-all default router in base.yml so a
		// tenant with a known plan gets its specific limit.
		fmt.Fprintf(&b, "      rule: \"PathPrefix(`/`) && Header(`X-Tenant-ID`, `%s`)\"\n", id)
		b.WriteString("      service: management-api\n")
		b.WriteString("      priority: 100\n")
		b.WriteString("      middlewares:\n")
		fmt.Fprintf(&b, "        - %s\n", mw)
	}
	return b.String()
}

// writeTenantGatewayConfig renders + atomically writes the dynamic config into
// dir/tenants.yml. No-op when dir is empty (non-gateway deployments).
func writeTenantGatewayConfig(dir string, plans map[string]string) error {
	if dir == "" {
		return nil
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("create traefik dynamic dir: %w", err)
	}
	data := []byte(renderTenantGatewayConfig(plans))

	// Atomic write: temp file in the same dir + rename, so Traefik's watcher
	// never observes a partial file. The temp name has NO yaml extension so the
	// file provider ignores it (it would otherwise try to parse, then fail to
	// find, the transient file).
	tmp, err := os.CreateTemp(dir, ".tenants-*.tmp")
	if err != nil {
		return err
	}
	tmpName := tmp.Name()
	defer os.Remove(tmpName)
	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		return err
	}
	// fsync so the rename can't expose an empty/partial file after a crash.
	if err := tmp.Sync(); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	// CreateTemp makes the file 0600; Traefik often runs as a non-root user, so
	// make it world-readable before publishing it.
	if err := os.Chmod(tmpName, 0o644); err != nil {
		return err
	}
	return os.Rename(tmpName, filepath.Join(dir, "tenants.yml"))
}
