apiVersion: v1
kind: Service
metadata:
  name: vrsky-filter
  namespace: vrsky-platform
  labels:
    app: vrsky-filter
    component: filter
    phase: 1e
spec:
  type: ClusterIP
  selector:
    app: vrsky-filter
  ports:
  - name: nats-client
    port: 9090
    targetPort: 9090
    protocol: TCP
  sessionAffinity: None
